### ISSUE TITLE
Discuss what to do with submitted links to projects hosted outside this repo ("awesome-list"?)

### ISSUE THREAD

**Issue by tildebyte** [pyscript/pyscript-collective#17]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a duplication

### What is the issue/comment/problem?

From a slightly [OT exchange][] at community.anaconda.cloud between @marimeireles and I:

Me:
> I had a question about CONTRIBUTING.MD, section “Contributing a new resource”: it says " The contributions in this topic are more similar to what an awesome-page would look like" - I’d like to put a link to my Github pages repo which has some demos made with pyscript. Should I open a PR where I add an “awesome-projects.md”, or will it be a GH wiki page, or something else entirely?

marimeireles:
> That’s a good question, what do you think it’s best?
> We’re still very much in the process of building that repo. I feel like in general an MD file has more visibility, but if you have any other ideas or models, I’m curious to hear thoughts.

[OT exchange]: https://community.anaconda.cloud/t/pyscript-p5-js/26128/17

**Comment by tildebyte** [comment]
I think that a markdown-formatted "awesome-list" would at least be a good start.

I've noticed that Github's repo wiki feature is actually kind of hard for people to discover...

A .md list also has the advantage that it renders natively on Github, and could even be moved into a "pages" repo for hosting...

I haven't finished my coffee, so that's all I have right now >_<

**Comment by pauleveritt** [comment]
Well said @tildebyte ... I think collecting a list of URLs pointing at examples, into an industry-standard "Awesome PyCharm" page, is probably our first order of business.

**Comment by marimeireles** [comment]
Seems great!
I think this is what @pauleveritt is quoting?
https://github.com/JetBrains/awesome-pycharm

**Comment by tildebyte** [comment]
I'm thinking 'awesome-resources.md' in the root of this repo, at least for now, along with an 'AWESOME-LIST-CONTRIBUTING.md', styled after the one in the PyCharm repo.

@marimeireles, @pauleveritt; what do y'all think?

**Comment by marimeireles** [comment]
Maybe we should combine the README with the Awesome List?
For better visualization.

**Comment by pauleveritt** [comment]
FTR, "awesome-pycharm" is a terribly un-awesome example of Awesome XYZ. 😀

I propose to make a section in the README pointing to an awesome-pyscript Markdown page. I'll do this via a new ticket.

In a second ticket, we'll figure out how to get this linked into the main site.

**Comment by tildebyte** [comment]
WDYT about CONTRIBUTING guidelines, a la [JetBrains/awesome-pycharm/CONTRIBUTING.md](https://github.com/JetBrains/awesome-pycharm/blob/master/CONTRIBUTING.md)?

I think they have a pretty solid document there (I already have a draft we could use :D).

IMO it could be inserted into the existing CONTRIBUTING, given that we already have a mention of an awesome-list in there.

**Comment by pauleveritt** [comment]
@tildebyte I'm about to make a ticket on some ideas that have been in-progress since the "collective" idea was first hatched. Hopefully post it in a couple of hours.

**Comment by pauleveritt** [comment]
I've started PR #28 with a first cut at the `awesome-pyscript` Markdown file. @jhanley-com is reviewing it. I'll keep scanning for more entries.

After that, still some more work: how to integrate it into the README, explain how to contribute, link to the main site.
