### ISSUE TITLE
Change project name from pyscript collective to PlanetPyScript

### ISSUE THREAD

**Issue by marimeireles** [pyscript/pyscript-collective#26]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a duplication

### What is the issue/comment/problem?

Since this project is very much a work in progress a few PyScript folks thought the name PlanetPyScript might be cooler than PyScript Collective.

It was proposed by @ntoll and his inspiration came from https://planetpython.org/

What do you all think about the change?

Votes as 👍 or 👎 ?

Any other thoughts? Add it down here!

**Comment by pauleveritt** [comment]
The hope is that the Collective is half work product (examples, Gallery) and half people (collaborators who onboard contributors into collaborators.) For me, the name "Collective" focuses on people, making it a more social endeavor.

I'm ok though with a different name.

**Comment by tildebyte** [comment]
I'm with Paul on this one.

Also, it's a cool name, but PlanetPython is really a news aggregator - not what we're doing here.

**Comment by marimeireles** [comment]
Alright, so I guess we don't.
Thanks folks.
